'use client'
import {useEffect,useState} from 'react'; import {supabase} from '../../lib/supabase'
type C={id:string;code:string;name:string;image_url:string}; type E={id:string;event_name:string;status:string;ends_at:string|null}
export default function Vote(){const [e,setE]=useState<E|null>(null),[cs,setCs]=useState<C[]>([]),[sel,setSel]=useState<string>(),[left,setLeft]=useState(0),[done,setDone]=useState(false)
async function load(){const {data:event}=await supabase.from('events').select('*').order('created_at',{ascending:false}).limit(1).maybeSingle();if(!event)return;setE(event);const {data}=await supabase.from('candidates').select('*').eq('event_id',event.id).order('sort_order');setCs(data||[])}
useEffect(()=>{load();const ch=supabase.channel('slay-vote').on('postgres_changes',{event:'*',schema:'public',table:'events'},load).subscribe();return()=>{supabase.removeChannel(ch)}},[])
useEffect(()=>{const t=setInterval(()=>setLeft(e?.ends_at?Math.max(0,Math.ceil((new Date(e.ends_at).getTime()-Date.now())/1000)):0),250);return()=>clearInterval(t)},[e])
async function vote(){if(!sel||!e||left<=0)return;const device=localStorage.getItem('slay-device')||crypto.randomUUID();localStorage.setItem('slay-device',device);const r=await fetch('/api/vote',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({eventId:e.id,candidateId:sel,deviceToken:device})});if(r.ok)setDone(true);else alert((await r.json()).error||'Không thể ghi nhận phiếu')}
if(done)return <main className="center"><div className="panel"><div className="eyebrow">THE SLAY LADY</div><h1 style={{fontSize:'clamp(46px,8vw,100px)'}}>ĐÃ GHI NHẬN</h1><p>Phiếu bình chọn của bạn đã được xác nhận.</p></div></main>
return <main className="screen"><div className="top"><div className="brand">BẢO LONG • THE SLAY LADY</div><div className="timer">00:{String(left).padStart(2,'0')}</div></div><div className="headline"><h1>WHO SLAYS TONIGHT?</h1><p>Chọn 01 đề cử bạn yêu thích nhất.</p></div><section className="grid">{cs.map(c=><article key={c.id} className={'candidate '+(sel===c.id?'selected':'')} onClick={()=>setSel(c.id)}><div className="photo">{c.image_url?<img src={c.image_url} alt={c.name}/>:<span>ẢNH ĐỀ CỬ</span>}</div><div className="meta"><b>{c.code}</b><div>{c.name}</div></div></article>)}</section><div style={{textAlign:'center',marginTop:24}}><button disabled={!sel||left<=0||e?.status!=='open'} onClick={vote}>XÁC NHẬN BÌNH CHỌN</button></div></main>}
